### ISSUE TITLE
Update "Likes" Count when book is added to a shelf

### ISSUE THREAD

**Issue by sjeremycohen** [gcivil-nyu-org/team-3-inperson#147]

**Comment by sjeremycohen** [comment]
https://pypi.org/project/django-pgtrigger/ - we should consider using this python module to implement postgres triggers within Django. This will make this so simple to accomplish within the database rather than having to build it into the add-remove code in the frontend

**Comment by emoltz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/147?planning-poker) with Zenhub @emoltz @michaelzachor @Pankhurinyu @rohan-sardana @sjeremycohen
