### ISSUE TITLE
frontend for onboarding page

### ISSUE THREAD

**Issue by emoltz** [gcivil-nyu-org/team-3-inperson#205]
The onboarding page is styled with genre data from the database, but not attached to the backend of the site yet. 

## Main components:
First, add favorite genres
Then, swipe on some books from our most popular books.

**Comment by sjeremycohen** [comment]
Homepage redirection:

IF User is not logged in:
     Redirect to sign in page
ELSE IF UserGenre Table is empty for the user:
     Redirect to onboarding
ELSE
     Redirect to book swiping
