### ISSUE TITLE
Swiping registers in rec engine

### ISSUE THREAD

**Issue by emoltz** [gcivil-nyu-org/team-3-inperson#247]

**Comment by emoltz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/247?planning-poker) with Zenhub @emoltz @michaelzachor @Pankhurinyu @rohan-sardana @sjeremycohen

**Comment by emoltz** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/247?planning-poker) with Zenhub @rohan-sardana

**Comment by rohan-sardana** [comment]
API endpoint (to communicate with rec engine): https://8kwwql5a02.execute-api.us-east-1.amazonaws.com/dev/

required query params- bid (book id of swiped book), direc (direction of the swipe), uid (user id)
