### ISSUE TITLE
Decide onto the NLP model for description matching

### ISSUE THREAD

**Issue by rohan-sardana** [gcivil-nyu-org/team-3-inperson#258]
Def of Done: Research about different NLP models that can be implemented in SageMaker to provide percentage of description matching of two books

**Comment by emoltz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/258?planning-poker) with Zenhub @emoltz @michaelzachor @Pankhurinyu @rohan-sardana @sjeremycohen
