### ISSUE TITLE
initial deployment

### ISSUE THREAD

**Issue by emoltz** [gcivil-nyu-org/team-3-inperson#53]
Definition of done: can be viewed on AWS site.

**Comment by emoltz** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/53?planning-poker) with Zenhub @Pankhurinyu

**Comment by emoltz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-3-632cb2260149e1002785f880/issues/gcivil-nyu-org/team-3-inperson/53?planning-poker) with Zenhub @michaelzachor @sjeremycohen

**Comment by emoltz** [comment]
Needs two deployments -- one dev, one production

**Comment by rohan-sardana** [comment]
dev-env created: http://tp-dev.eba-jmv3wnbt.us-east-1.elasticbeanstalk.com/
